// Generated by jextract

package org.python;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct _longobject {
 *     PyVarObject ob_base;
 *     digit ob_digit[1];
 * }
 * }
 */
public class _longobject {

    _longobject() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        PyVarObject.layout().withName("ob_base"),
        MemoryLayout.sequenceLayout(1, Python_h.C_INT).withName("ob_digit"),
        MemoryLayout.paddingLayout(4)
    ).withName("_longobject");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout ob_base$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("ob_base"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * PyVarObject ob_base
     * }
     */
    public static final GroupLayout ob_base$layout() {
        return ob_base$LAYOUT;
    }

    private static final long ob_base$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * PyVarObject ob_base
     * }
     */
    public static final long ob_base$offset() {
        return ob_base$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * PyVarObject ob_base
     * }
     */
    public static MemorySegment ob_base(MemorySegment struct) {
        return struct.asSlice(ob_base$OFFSET, ob_base$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * PyVarObject ob_base
     * }
     */
    public static void ob_base(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, ob_base$OFFSET, ob_base$LAYOUT.byteSize());
    }

    private static final SequenceLayout ob_digit$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("ob_digit"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * digit ob_digit[1]
     * }
     */
    public static final SequenceLayout ob_digit$layout() {
        return ob_digit$LAYOUT;
    }

    private static final long ob_digit$OFFSET = 24;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * digit ob_digit[1]
     * }
     */
    public static final long ob_digit$offset() {
        return ob_digit$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * digit ob_digit[1]
     * }
     */
    public static MemorySegment ob_digit(MemorySegment struct) {
        return struct.asSlice(ob_digit$OFFSET, ob_digit$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * digit ob_digit[1]
     * }
     */
    public static void ob_digit(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, ob_digit$OFFSET, ob_digit$LAYOUT.byteSize());
    }

    private static long[] ob_digit$DIMS = { 1 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * digit ob_digit[1]
     * }
     */
    public static long[] ob_digit$dimensions() {
        return ob_digit$DIMS;
    }
    private static final VarHandle ob_digit$ELEM_HANDLE = ob_digit$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * digit ob_digit[1]
     * }
     */
    public static int ob_digit(MemorySegment struct, long index0) {
        return (int)ob_digit$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * digit ob_digit[1]
     * }
     */
    public static void ob_digit(MemorySegment struct, long index0, int fieldValue) {
        ob_digit$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

